let stockProductos = [
    {id: 1, nombre: "Golf MK4 GTI", cantidad: 1, desc: "Volkswagen golf MK4 GTI transmion manual", precio: 2500000, marca: "Volkswagen", img: './img/golfMK4.jpg'},
    {id: 2, nombre: "Golf MK5 GTI", cantidad: 1, desc: "Volkswagen golf MK5 GTI transmision manual", precio: 3500000, marca: "Volkswagen", img: './img/golfMK5.jpg'},
    {id: 3, nombre: "Golf MK6 GTI", cantidad: 1, desc: "Volkswagen golf MK6 GTI transmision automatica", precio: 6900000, marca: "Volkswagen", img: './img/golfMK6GTI.jpg'},
    {id: 4, nombre: "Golf MK6 R", cantidad: 1, desc: "Volkswagen golf MK6 R transmision automatica", precio: 8500000, marca: "Volkswagen", img: './img/golfMK6R.jpg'},
    {id: 5, nombre: "Golf MK7 GTI", cantidad: 1, desc: "Volkswagen golf MK7 GTI transmision automatica", precio: 9000000, marca: "Volkswagen", img: './img/golfMK7GTI.jpg'},
    {id: 6, nombre: "Golf MK7 R", cantidad: 1, desc: "Volkswagen golf MK7 R transmision automatica", precio: 12000000, marca: "Volkswagen", img: './img/golfMK7R.jpg'},
    {id: 7, nombre: "Scirocco GTS", cantidad: 1, desc: "Volkswagen scirocco GTS transmision automatica", precio: 10500000, marca: "Volkswagen", img: './img/sciroccoGTS.jpg'},
    {id: 8, nombre: "Scirocco R", cantidad: 1, desc: "Volkswagen scirocco R transmision automatica", precio: 15000000, marca: "Volkswagen", img: './img/sciroccoR.jpg'},
    {id: 9, nombre: "Gol Trend", cantidad: 1, desc: "Volkswagen gol transmision manual", precio: 3000000, marca: "Volkswagen", img: './img/golTrend.jpg'},
    {id: 10, nombre: "Bora 1.8T", cantidad: 1, desc: "Volkswagen bora 1.8 T transmision manual", precio: 2500000, marca: "Volkswagen", img: './img/bora.jpg'},
    {id: 11, nombre: "Golf MK4 R32", cantidad: 1,desc: "Volkswagen golf MK4 R32 transimision manual", precio: 3500000, marca: "Volkswagen", img: './img/golfMK4R32.jpg'},
    {id: 12, nombre: "Golf MK5 R32", cantidad: 1, desc: "Volkswagen golf MK5 R32 transmision automatica", precio: 5000000, marca: "Volkswagen", img: './img/golfMK5R32.jpg'},
    {id: 13, nombre: "Audi R8", cantidad: 1, desc: "Audi R8 transmision automatica", precio: 70500000, marca: "Audi", img: './img/audiR8.jpg'},
    {id: 14, nombre: "BMW M3", cantidad: 1, desc: "BMW M3 transmision automatica", precio: 27600000, marca: "BMW", img: './img/bmwM3.jpg'},
    {id: 15, nombre: "BMW M4", cantidad: 1, desc: "BMW M4 transmision automatica", precio: 37500000, marca: "BMW", img: './img/bmwM4.jpg'},
    {id: 16, nombre: "BMW M3 E90", cantidad: 1, desc: "BMW M3 E90 transmision manual", precio: 5000000, marca: "BMW", img: './img/bmwE90.jpg'},
    {id: 17, nombre: "Nissan 370 Z", cantidad: 1, desc: "Nissan 370 Z transmision automatica", precio: 12000000, marca: "Nissan", img: './img/nissan370.jpg'},
    {id: 18, nombre: "Nissan Skyline R34", cantidad: 1, desc: "Nissan Skyline GTR R34 transmision manual", precio: 75000000, marca: "Nissan", img: './img/r34.jpg'},
    {id: 19, nombre: "Nissan Skyline R35", cantidad: 1, desc: "Nissan Skyline GTR R35", precio: 85000000, marca: "Nissan", img: './img/r35.jpg'},
    {id: 20, nombre: "Subaru BRZ", cantidad: 1, desc: "Subaru BRZ transmision automatica", precio: 95000000, marca: "Subaru", img: './img/subaruBRZ.jpg'},
    {id: 21, nombre: "Chevrolet Cruze LTZ", cantidad: 1, desc: "Chevrolet Cruze LTZ transmision automatica", precio: 5500000, marca: "Chevrolet", img: './img/cruzeCorto.jpg'},
    {id: 22, nombre: "Chevrolet Cruze LTZ", cantidad: 1, desc: "Chevrolet Cruze LTZ transmision manual", precio: 5500000, marca: "Chevrolet", img: './img/cruzeLargo.jpg'},
    {id: 23, nombre: "Toyota 86", cantidad: 1, desc: "Toyota 86 transmision automatica", precio: 10500000, marca: "Toyota", img: './img/toyota86.jpg'},
    {id: 24, nombre: "Hyundai Genesis", cantidad: 1, desc: "Hyundai Genesis coupe", precio: 6000000, marca: "Hyundai", img: './img/hyundai.jpg'},]